# Simulator settings
SIM ?= verilator
TOPLEVEL_LANG ?= verilog

# RTL Sources
VERILOG_SOURCES += $(PWD)/../../rtl/phx_delay_line.sv

# Top-level module name (in your .sv file)
TOPLEVEL = phx_delay_line

# Python test file name (without .py)
MODULE = test_phx_delay_line

# Verilator specific flags
ifeq ($(SIM), verilator)
    # Enable VCD tracing
    EXTRA_ARGS += --trace --trace-structs
endif

# Include cocotb's make rules
include $(shell cocotb-config --makefiles)/Makefile.sim
