# Project Phoenix - Standardized Simulation Engine

# ------------------------------------------------------------------------------
# 1. Project Configuration
# ------------------------------------------------------------------------------
DUT					?=	phx_delay_line
RTL_DIR			?= ../../rtl
LIB_DIR 		?= ../../lib
PHX_SRC_DIR ?= $(LIB_DIR)/phoenix/src

SIM ?= verilator
TOPLEVEL_LANG ?= verilog

# Cocotb Configuration
TOPLEVEL = $(DUT)
MODULE = test_$(DUT)

# Verilator specific flags
ifeq ($(SIM), verilator)
    # Enable VCD tracing
    EXTRA_ARGS += --trace --trace-structs
endif

# ------------------------------------------------------------------------------
# 2. Auto-Discovery Functions
# ------------------------------------------------------------------------------
# Function: process_f_files
# Logic: Look at a list of strings. If a string ends in .f, go inside it. 
# Otherwise, keep the filename as is.
process_f_files = $(foreach f,$1,$(if $(filter %.f,$f),$(call process_f_file,$f),$f))
# Function: process_f_file
# Logic: Read the .f file, add its directory as a prefix to everything inside,
# and then call process_f_files again to see if there are more nested .f files.
process_f_file = $(call process_f_files,$(addprefix $(dir $1),$(shell cat $1)))

# ------------------------------------------------------------------------------
# 3. RTL Source Discovery
# ------------------------------------------------------------------------------
# if .f exists, use it: otherwise, fallback to the .sv file
ifneq ($(wildcard $(RTL_DIR)/$(DUT).f),)
	VERILOG_SOURCES += $(call process_f_files, $(RTL_DIR)/$(DUT).f)
else 
	VERILOG_SOURCES += $(RTL_DIR)/$(DUT).sv
endif

# ------------------------------------------------------------------------------
# 4. Cocotb's Make Rules  
# ------------------------------------------------------------------------------
include $(shell cocotb-config --makefiles)/Makefile.sim

# ------------------------------------------------------------------------------
# 5. Execution Rules
# ------------------------------------------------------------------------------
waves: 
	@if [ ! -f dump.vcd ]; then make; fi
	gtkwave dump.vcd

.PHONY: waves help clean
